version: "3.7"
services:
    service:
        build:
            context: .
            dockerfile: ./service/Dockerfile
        ports:
            - "8000:8000"
        networks:
            - web-app
    ui:
        build:
            context: .
            dockerfile: ./ui/Dockerfile
        ports:
            - "4200:4200"
        networks:
            - web-app
    db:
        image: mongo:3.4-xenial
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        networks: 
            - web-app

networks:
    web-app:
